services:
  backend:
    image: ghcr.io/kore29/volta:latest
    pull_policy: always
    container_name: volta-backend
    restart: always
    env_file:
      - /opt/docker/volta/.env
    volumes:
      - wwebjs-auth:/app/backend/.wwebjs_auth
    command: npm run --workspace=backend start
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: ghcr.io/kore29/volta:latest
    pull_policy: always
    container_name: volta-frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - /opt/docker/volta/.env
    command: npm run --workspace=frontend start
    ports:
      - "${PORT_HOST:-3001}:${PORT:-3000}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  wwebjs-auth:
