-- AlterTable
ALTER TABLE "Business" ADD COLUMN     "borderRadiusLevel" TEXT NOT NULL DEFAULT 'MEDIUM',
ADD COLUMN     "fontSizeLevel" TEXT NOT NULL DEFAULT 'MEDIUM',
ADD COLUMN     "themeColor" TEXT NOT NULL DEFAULT 'CLINICAL_ELEGANCE';
