export const COLOR_PALETTES = {
  CLINICAL_ELEGANCE: {
    name: "Elegancia Clínica (Defecto)",
    surface: '#f8fafa',
    surfaceDim: '#d8dada',
    surfaceBright: '#f8fafa',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f2f4f4',
    surfaceContainer: '#eceeee',
    surfaceContainerHigh: '#e6e8e9',
    surfaceContainerHighest: '#e1e3e3',
    onSurface: '#191c1d',
    onSurfaceVariant: '#3e4949',
    inverseSurface: '#2e3131',
    inverseOnSurface: '#eff1f1',
    outline: '#6e7979',
    outlineVariant: '#bdc9c8',
    surfaceTint: '#006a6a',
    primary: '#006565',
    onPrimary: '#ffffff',
    primaryContainer: '#008080',
    onPrimaryContainer: '#e3fffe',
    inversePrimary: '#76d6d5',
    secondary: '#4c6262',
    onSecondary: '#ffffff',
    secondaryContainer: '#cce4e4',
    onSecondaryContainer: '#516767',
    tertiary: '#4c5a78',
    onTertiary: '#ffffff',
    tertiaryContainer: '#657392',
    onTertiaryContainer: '#faf9ff',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    primaryFixed: '#93f2f2',
    primaryFixedDim: '#76d6d5',
    onPrimaryFixed: '#002020',
    onPrimaryFixedVariant: '#004f4f',
    secondaryFixed: '#cfe7e7',
    secondaryFixedDim: '#b3cbcb',
    onSecondaryFixed: '#081f1f',
    onSecondaryFixedVariant: '#354b4b',
    tertiaryFixed: '#d8e2ff',
    tertiaryFixedDim: '#b8c6e9',
    onTertiaryFixed: '#0c1b36',
    onTertiaryFixedVariant: '#394763',
    background: '#f8fafa',
    onBackground: '#191c1d',
    surfaceVariant: '#e1e3e3',
  },
  ORCHID_SERENITY: {
    name: "Orquídea Serena",
    surface: '#f8f9ff',
    surfaceDim: '#ccdbf4',
    surfaceBright: '#f8f9ff',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#eff4ff',
    surfaceContainer: '#e5eeff',
    surfaceContainerHigh: '#dce9ff',
    surfaceContainerHighest: '#d4e4fc',
    onSurface: '#0d1c2e',
    onSurfaceVariant: '#524343',
    inverseSurface: '#223144',
    inverseOnSurface: '#eaf1ff',
    outline: '#857372',
    outlineVariant: '#d7c2c1',
    surfaceTint: '#8a4d4e',
    primary: '#8a4d4e',
    onPrimary: '#ffffff',
    primaryContainer: '#d48c8c',
    onPrimaryContainer: '#592628',
    inversePrimary: '#ffb3b3',
    secondary: '#545f72',
    onSecondary: '#ffffff',
    secondaryContainer: '#d5e0f7',
    onSecondaryContainer: '#586377',
    tertiary: '#615d5e',
    onTertiary: '#ffffff',
    tertiaryContainer: '#a39e9e',
    onTertiaryContainer: '#393536',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    primaryFixed: '#ffdad9',
    primaryFixedDim: '#ffb3b3',
    onPrimaryFixed: '#380c0f',
    onPrimaryFixedVariant: '#6e3637',
    secondaryFixed: '#d8e3fa',
    secondaryFixedDim: '#bcc7dd',
    onSecondaryFixed: '#111c2c',
    onSecondaryFixedVariant: '#3c475a',
    tertiaryFixed: '#e8e1e1',
    tertiaryFixedDim: '#cbc5c5',
    onTertiaryFixed: '#1d1b1b',
    onTertiaryFixedVariant: '#494646',
    background: '#f8f9ff',
    onBackground: '#0d1c2e',
    surfaceVariant: '#d4e4fc',
  },
  ORGANIC_VITALITY: {
    name: "Vitalidad Orgánica",
    surface: '#f6fce1',
    surfaceDim: '#d7ddc3',
    surfaceBright: '#f6fce1',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f0f7dc',
    surfaceContainer: '#eaf1d6',
    surfaceContainerHigh: '#e5ebd0',
    surfaceContainerHighest: '#dfe5cb',
    onSurface: '#181e0d',
    onSurfaceVariant: '#444939',
    inverseSurface: '#2d3321',
    inverseOnSurface: '#edf4d9',
    outline: '#747967',
    outlineVariant: '#c4c9b4',
    surfaceTint: '#496800',
    primary: '#476500',
    onPrimary: '#ffffff',
    primaryContainer: '#5d7f13',
    onPrimaryContainer: '#faffe7',
    inversePrimary: '#add461',
    secondary: '#676014',
    onSecondary: '#ffffff',
    secondaryContainer: '#efe58b',
    onSecondaryContainer: '#6d661a',
    tertiary: '#5a5d56',
    onTertiary: '#ffffff',
    tertiaryContainer: '#72766e',
    onTertiaryContainer: '#fbfdf4',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    primaryFixed: '#c8f17a',
    primaryFixedDim: '#add461',
    onPrimaryFixed: '#131f00',
    onPrimaryFixedVariant: '#364e00',
    secondaryFixed: '#efe58b',
    secondaryFixedDim: '#d2c972',
    onSecondaryFixed: '#1f1c00',
    onSecondaryFixedVariant: '#4e4800',
    tertiaryFixed: '#e1e3db',
    tertiaryFixedDim: '#c5c7bf',
    onTertiaryFixed: '#191d17',
    onTertiaryFixedVariant: '#444841',
    background: '#f6fce1',
    onBackground: '#181e0d',
    surfaceVariant: '#dfe5cb',
  },
  WARM_SAND: {
    name: "Arena Cálida",
    surface: '#fff8f4',
    surfaceDim: '#e1d8d3',
    surfaceBright: '#fff8f4',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#fbf2ec',
    surfaceContainer: '#f5ece6',
    surfaceContainerHigh: '#efe6e1',
    surfaceContainerHighest: '#eae1db',
    onSurface: '#1f1b18',
    onSurfaceVariant: '#54433e',
    inverseSurface: '#34302c',
    inverseOnSurface: '#f8efe9',
    outline: '#87736c',
    outlineVariant: '#dac1ba',
    surfaceTint: '#934930',
    primary: '#934930',
    onPrimary: '#ffffff',
    primaryContainer: '#d17a5d',
    onPrimaryContainer: '#501703',
    inversePrimary: '#ffb59d',
    secondary: '#645d56',
    onSecondary: '#ffffff',
    secondaryContainer: '#ebe1d8',
    onSecondaryContainer: '#6a635c',
    tertiary: '#5f5e5b',
    onTertiary: '#ffffff',
    tertiaryContainer: '#92918d',
    onTertiaryContainer: '#2a2a27',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    primaryFixed: '#ffdbd0',
    primaryFixedDim: '#ffb59d',
    onPrimaryFixed: '#390c00',
    onPrimaryFixedVariant: '#76331b',
    secondaryFixed: '#ebe1d8',
    secondaryFixedDim: '#cec5bc',
    onSecondaryFixed: '#1f1b16',
    onSecondaryFixedVariant: '#4c463f',
    tertiaryFixed: '#e5e2dd',
    tertiaryFixedDim: '#c8c6c2',
    onTertiaryFixed: '#1c1c19',
    onTertiaryFixedVariant: '#474743',
    background: '#fff8f4',
    onBackground: '#1f1b18',
    surfaceVariant: '#eae1db',
  }
};

export const FONT_SCALES = {
  SMALL: { name: "Pequeño", scale: "0.9" },
  MEDIUM: { name: "Mediano", scale: "1.0" },
  LARGE: { name: "Grande", scale: "1.15" }
};

export const RADIUS_SCALES = {
  SMALL: { name: "Recto", scale: "0.0" },
  MEDIUM: { name: "Suave", scale: "1.0" },
  LARGE: { name: "Muy Redondeado", scale: "2.0" }
};

export function getThemeColor(color: string | null | undefined): keyof typeof COLOR_PALETTES {
  if (!color) return "CLINICAL_ELEGANCE";
  const mapped: Record<string, string> = {
    TEAL: "CLINICAL_ELEGANCE",
    INDIGO: "CLINICAL_ELEGANCE",
    ROSE: "ORCHID_SERENITY",
    AMBER: "WARM_SAND",
    EMERALD: "ORGANIC_VITALITY",
    CLINICAL_ELEGANCE: "CLINICAL_ELEGANCE",
    ORCHID_SERENITY: "ORCHID_SERENITY",
    ORGANIC_VITALITY: "ORGANIC_VITALITY",
    WARM_SAND: "WARM_SAND",
  };
  const target = mapped[color.toUpperCase()] || color.toUpperCase();
  return (target in COLOR_PALETTES ? target : "CLINICAL_ELEGANCE") as keyof typeof COLOR_PALETTES;
}

export function getThemeInlineStyles(
  palette: typeof COLOR_PALETTES[keyof typeof COLOR_PALETTES],
  fontScale: string,
  radiusScale: string
): Record<string, string> {
  const styles: Record<string, string> = {
    "--font-scale": fontScale,
    "--radius-scale": radiusScale,
  };

  Object.entries(palette).forEach(([key, val]) => {
    if (key === "name") return;
    // camelCase to kebab-case (e.g. primaryContainer -> --color-primary-container)
    const cssVarName = `--color-${key.replace(/([A-Z])/g, "-$1").toLowerCase()}`;
    styles[cssVarName] = val as string;
  });

  return styles;
}

export function applyThemeColors(
  root: HTMLElement,
  palette: typeof COLOR_PALETTES[keyof typeof COLOR_PALETTES]
) {
  Object.entries(palette).forEach(([key, val]) => {
    if (key === "name") return;
    const cssVarName = `--color-${key.replace(/([A-Z])/g, "-$1").toLowerCase()}`;
    root.style.setProperty(cssVarName, val as string);
  });
}

